services:
  backend:
    build: .
    depends_on:
      - db
    ports:
      - '8000:3000'

  db:
    image: 'mysql:8.0.3'
    ports:
      - '8080:3306'
    expose:
      - '8080'
    restart: always
    command: --default-authentication-plugin=mysql_native_password # Important for disabling SSL; insecure but this is supposed to work
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_TCP_PORT=8080
